version: '3.8'
services:
  api:
    build: .
    ports:
      - '5000:5000'
    volumes:
      - .:/app
    container_name: api
    env_file:
      - .env
    environment:
      - MONGO_URL=mongodb://mongodb:27017
  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongodb:/data/db
volumes:
  mongodb: