
GET http://localhost:5000/api/v1/hotels
Accept: application/json

### GET ALL Hotels

GET http://localhost:5000/api/v1/hotels/6485f07c40ba2faab7ec46cb
Accept: application/json

### GET Hotel BY ID


POST http://localhost:5001/api/v1/hotels/
Content-Type: application/json

{
  "name": "SECOND HOTEL",
  "Location": "TEHRAN"
}

### Create Hotel

PUT http://localhost:5001/api/v1/hotels/6486ed8b4d6f76456dec1032
Content-Type: application/json

{
  "Location": "IRAN"
}

### Update Hotel