
GET http://localhost:5001/api/v1/users
Accept: application/json

### GET ALL USERS

GET http://localhost:5001/api/v1/users/648189f346341105099d14ff
Accept: application/json

### GET USER BY ID

POST http://localhost:5001/api/v1/users
Content-Type: application/json

{
  "email": "user@gmail.com",
  "password": "UserPassword"
}

### CREATE USER

DELETE http://localhost:5001/api/v1/users/64818c11958b0e476107cac1
Content-Type: application/json


### DELETE USER